### ISSUE TITLE
"no source file found" with double backslash in the path

### ISSUE THREAD

**Issue by sowsem** [frerich/clcache#100]
Hi!

I am trying to make clcache work with my cmake-based project. I have been able to actually make bypass an error in clcache just by removing \Zi flags that looks not to be supported.

Unfortunately, looks like there is another problem when using clcache in my project: it complains about being unable to find each single source file for actually caching it for later compilations. I get tons of  "passed to the real compiler" hits in the clcache stats. The error is always the same: no source file found. 

This is a sample of the kind of log I get from clcache:

C:\dev\clcache\dist\clcache.py Cannot cache invocation as ['/nologo', u'/c', u'/I"C:\\dev\\project\\common\\include"' /Fd"Bullet2FileLoader.dir\\Debug\\vc120.pdb" /Gd /TP /wd4201 /wd4512 /analyze- /errorReport:queue "C:\\dev\\project\\src\\Bullet3Serialize\\Bullet2FileLoader\\b3Serializer.cpp"']: no source file found
  
Any idea how to fix this issue or if there is actually an issue in clcache itself?

**Comment by frerich** [comment]
It looks like the quotation marks after /I and /Fd are confusing the command line parser. I'll have a look.

**Comment by sowsem** [comment]
Cool!. As a side note it is being run from cygwin... just in case!

**Comment by frerich** [comment]
Two things - can you please reproduce this error but with having the `CLCACHE_LOG` environment variable set? That'll make clcache print all kinds of debugging information about what it does.In particular, it should print two lines saying `Parsing given command line...` and `Expanded commandline` -- can you send those lines?

Also, it would be perfect if you could give the actual `cl` command line which is invoked, you can possibly get that by building your CMake project with `make VERBOSE=1`.

**Comment by sowsem** [comment]
Sure. The log variable is already set. Will do when I get  to my laptop later today hopefully! Thx!

**Comment by webmaster128** [comment]
The command line is parsed as 3 arguments only, which is an error

* `/nologo`
* `/c`
* `/I"C:\dev\project\common\include"' /Fd"Bullet2FileLoader.dir\Debug\vc120.pdb" /Gd /TP /wd4201 /wd4512 /analyze- /errorReport:queue "C:\dev\project\src\Bullet3Serialize\Bullet2FileLoader\b3Serializer.cpp"`

What I find strange is that there is exactly one single quote in this part

```
                                 v
/I"C:\dev\project\common\include"' /Fd"Bullet2FileLoader.dir\Debug\vc120.pdb" /Gd /TP /wd4201 /wd4512 /analyze- /errorReport:queue "C:\dev\project\src\Bullet3Serialize\Bullet2FileLoader\b3Serializer.cpp"
```

**Comment by sowsem** [comment]
Will put the real sample, even being so long line. Just in case is also a argument list length problem!
`C:\dev\clcache\dist\clcache.py Parsing given commandline '['/nologo', '@C:\\Program Files (x86)\\Xoreax\\IncrediBuild\\temp\\ib_1A847.tmp']'



C:\dev\clcache\dist\clcache.py Expanded commandline '['/nologo', u'/c', u'/I"C:\\dev\\projects\\projectx-client\\packages\\projectx-common\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\projectxsandbox\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\projectxbuilder\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\lua-wrapper\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\project1-config\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\application\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\application\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\buildinfo\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\config\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\application-util\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\keyvalue\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\audio\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\containers\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\util\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\containers-util\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\effects\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\filesystem\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\filesystem\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\libzip\\1.0.1\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\zlib\\1.2.5\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\gameutil\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\gui\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\image\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\input\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\input\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\json\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\rapidjson\\0.11\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\localization\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\logging\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\math\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\notification\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\profiler\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\property\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\renderer\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\renderutil\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\resources\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\entitycomponentsystem\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\scene\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\system\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\project1-version\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\device\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\device\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\web\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\uri\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\xml\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\thirdparty\\lua\\5.2.2\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\projectxtracking\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\king-sdk\\king-sdk\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\dependo-packages\\ksdkinternal-events\\include"', u'/I"C:\\dev\\projects\\projectx-client\\projectx\\KRAL\\..\\..\\generated-packages\\anvil\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\http\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\http\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\curl\\7.30.0\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\openssl\\1.0.1t\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\openssl\\1.0.1t\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\tcp\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\tcp\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\jsonrpc\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\dependo-packages\\plataforma-clientapi\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\extensions\\juego\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\dependo-packages\\juego-api\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\plataforma\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\crosskingapp\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\plataforma-common\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\gameplatform-config\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\dependo-packages\\king_constants\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\social\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\gameplatform-utils\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\network\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\king-fonts\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\recastnavigation\\0.1.0\\recastnavigation\\Recast\\Include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\recastnavigation\\0.1.0\\recastnavigation\\Detour\\Include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\recastnavigation\\0.1.0\\recastnavigation\\DetourCrowd\\Include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\recastnavigation\\0.1.0\\recastnavigation\\DetourTileCache\\Include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\recastnavigation\\0.1.0\\recastnavigation\\DebugUtils\\Include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\console\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\guisystem\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\projectxrender\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\editor-shared\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\analytics\\crash-info-sender\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\crashreport\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\dependo-packages\\crashanalytics\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\breadcrumbs\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\servicelayer-views\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\ff-ksdk-integration\\packages\\ff-ksdk\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\ff-ksdk-integration\\packages\\ff-ksdk-servicelayer-views\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\servicelayer\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\king-sdk\\ksdk-juego\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\saga-map\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\timelines\\include"', u'/I"C:\\dev\\projects\\projectx-client\\automation\\jwpserver\\jwp-http-server\\dev\\include"', u'/I"C:\\dev\\projects\\projectx-client\\automation\\jwpserver\\core-jwp\\include"', u'/I"C:\\dev\\projects\\projectx-client\\automation\\jwpserver\\web-console\\include"', u'/I"C:\\dev\\projects\\projectx-client\\automation\\jwpserver\\thirdparty\\mongoose\\5.3\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\gtest\\1.7.0\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\gmock\\1.7.0\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\testutil\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\mem-leaks-util\\include"', u'/I"C:\\dev\\projects\\projectx-client\\projectx\\KRAL\\..\\..\\generated-packages\\projectx-clientapis\\include"', u'/I"C:\\dev\\projects\\projectx-client\\projectx\\KRAL\\..\\..\\generated-packages\\perfilador-generated\\include"', u'/I"C:\\dev\\projects\\projectx-client\\projectx\\KRAL\\..\\..\\generated-packages\\perfilador-client\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\bullet\\2.83.4\\src"', u'/Z7', u'/W4', u'/WX-', u'/MP', u'/Od', u'/Ob0', u'/Oy-', u'/D', u'_CRT_SECURE_NO_WARNINGS', u'/D', u'WIN32', u'/D', u'FF_MEMORY_MANAGER=1', u'/D', u'FF_DYNAMIC_PROPERTIES', u'/D', u'_VARIADIC_MAX=10', u'/D', u'FSM_DEBUG', u'/D', u'USE_DEFAULT_FF_MESH_RENDER_FOR_DEBUG_DRAW', u'/D', u'FF_DEBUG_STRING_ID=1', u'/D', u'TESTS', u'/D', u'FSM_DEBUG', u'/D', u'FF_DEBUG_STRING_ID=1', u'/D', u'JWP_WEBDRIVER_ENABLED', u'/D', u'_DEBUG', u'/D', u'_DEBUG', u'/D', u'_CRT_SECURE_NO_WARNINGS', u'/D', u'_CRT_SECURE_NO_DEPRECATE', u'/D', u'_SCL_SECURE_NO_WARNINGS', u'/D', u'NO_OPENGL3', u'/D', u'CMAKE_INTDIR=\\"Debug\\"', u'/D', u'_MBCS', u'/Gm-', u'/EHsc', u'/RTC1', u'/MTd', u'/GS', u'/arch:SSE', u'/fp:fast', u'/Zc:wchar_t', u'/Zc:forScope', u'/Fo"Bullet2FileLoader.dir\\Debug\\\\" /Fd"Bullet2FileLoader.dir\\Debug\\vc120.pdb" /Gd /TP /wd4201 /wd4512 /analyze- /errorReport:queue "C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\bullet\\2.83.4\\src\\Bullet3Serialize\\Bullet2FileLoader\\b3Serializer.cpp"']'


C:\dev\clcache\dist\clcache.py Cannot cache invocation as ['/nologo', u'/c', u'/I"C:\\dev\\projects\\projectx-client\\packages\\projectx-common\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\projectxsandbox\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\projectxbuilder\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\lua-wrapper\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\project1-config\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\application\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\application\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\buildinfo\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\config\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\application-util\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\keyvalue\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\audio\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\containers\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\util\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\containers-util\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\effects\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\filesystem\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\filesystem\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\libzip\\1.0.1\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\zlib\\1.2.5\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\gameutil\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\gui\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\image\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\input\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\input\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\json\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\rapidjson\\0.11\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\localization\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\logging\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\math\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\notification\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\profiler\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\property\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\renderer\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\renderutil\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\resources\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\entitycomponentsystem\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\scene\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\system\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\project1-version\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\device\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\device\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\web\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\uri\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\xml\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\thirdparty\\lua\\5.2.2\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\projectxtracking\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\king-sdk\\king-sdk\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\dependo-packages\\ksdkinternal-events\\include"', u'/I"C:\\dev\\projects\\projectx-client\\projectx\\KRAL\\..\\..\\generated-packages\\anvil\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\http\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\http\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\curl\\7.30.0\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\openssl\\1.0.1t\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\openssl\\1.0.1t\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\tcp\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\tcp\\platform_include\\win32"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\jsonrpc\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\dependo-packages\\plataforma-clientapi\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\extensions\\juego\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\dependo-packages\\juego-api\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\plataforma\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\crosskingapp\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\plataforma-common\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\gameplatform-config\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\dependo-packages\\king_constants\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\social\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\gameplatform-utils\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\platform\\network\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\king-fonts\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\recastnavigation\\0.1.0\\recastnavigation\\Recast\\Include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\recastnavigation\\0.1.0\\recastnavigation\\Detour\\Include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\recastnavigation\\0.1.0\\recastnavigation\\DetourCrowd\\Include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\recastnavigation\\0.1.0\\recastnavigation\\DetourTileCache\\Include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\recastnavigation\\0.1.0\\recastnavigation\\DebugUtils\\Include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projectyb3Serializer.cpp
  \\project1\\packages\\core\\console\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\guisystem\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\projectxrender\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\editor-shared\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\analytics\\crash-info-sender\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\crashreport\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\dependo-packages\\crashanalytics\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\breadcrumbs\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\servicelayer-views\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\ff-ksdk-integration\\packages\\ff-ksdk\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\ff-ksdk-integration\\packages\\ff-ksdk-servicelayer-views\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\base-sdk\\servicelayer\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectplatform\\packages\\king-sdk\\ksdk-juego\\include"', u'/I"C:\\dev\\projects\\projectx-client\\packages\\saga-map\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\project1\\packages\\core\\timelines\\include"', u'/I"C:\\dev\\projects\\projectx-client\\automation\\jwpserver\\jwp-http-server\\dev\\include"', u'/I"C:\\dev\\projects\\projectx-client\\automation\\jwpserver\\core-jwp\\include"', u'/I"C:\\dev\\projects\\projectx-client\\automation\\jwpserver\\web-console\\include"', u'/I"C:\\dev\\projects\\projectx-client\\automation\\jwpserver\\thirdparty\\mongoose\\5.3\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\gtest\\1.7.0\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\thirdparty\\gmock\\1.7.0\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\testutil\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\projecty\\projectcore\\packages\\core\\mem-leaks-util\\include"', u'/I"C:\\dev\\projects\\projectx-client\\projectx\\KRAL\\..\\..\\generated-packages\\projectx-clientapis\\include"', u'/I"C:\\dev\\projects\\projectx-client\\projectx\\KRAL\\..\\..\\generated-packages\\perfilador-generated\\include"', u'/I"C:\\dev\\projects\\projectx-client\\projectx\\KRAL\\..\\..\\generated-packages\\perfilador-client\\include"', u'/I"C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\bullet\\2.83.4\\src"', u'/Z7', u'/W4', u'/WX-', u'/MP', u'/Od', u'/Ob0', u'/Oy-', u'/D', u'_CRT_SECURE_NO_WARNINGS', u'/D', u'WIN32', u'/D', u'FF_MEMORY_MANAGER=1', u'/D', u'FF_DYNAMIC_PROPERTIES', u'/D', u'_VARIADIC_MAX=10', u'/D', u'FSM_DEBUG', u'/D', u'USE_DEFAULT_FF_MESH_RENDER_FOR_DEBUG_DRAW', u'/D', u'FF_DEBUG_STRING_ID=1', u'/D', u'TESTS', u'/D', u'FSM_DEBUG', u'/D', u'FF_DEBUG_STRING_ID=1', u'/D', u'JWP_WEBDRIVER_ENABLED', u'/D', u'_DEBUG', u'/D', u'_DEBUG', u'/D', u'_CRT_SECURE_NO_WARNINGS', u'/D', u'_CRT_SECURE_NO_DEPRECATE', u'/D', u'_SCL_SECURE_NO_WARNINGS', u'/D', u'NO_OPENGL3', u'/D', u'CMAKE_INTDIR=\\"Debug\\"', u'/D', u'_MBCS', u'/Gm-', u'/EHsc', u'/RTC1', u'/MTd', u'/GS', u'/arch:SSE', u'/fp:fast', u'/Zc:wchar_t', u'/Zc:forScope', u'/Fo"Bullet2FileLoader.dir\\Debug\\\\" /Fd"Bullet2FileLoader.dir\\Debug\\vc120.pdb" /Gd /TP /wd4201 /wd4512 /analyze- /errorReport:queue "C:\\dev\\projects\\projectx-client\\engine\\thirdparty\\bullet\\2.83.4\\src\\Bullet3Serialize\\Bullet2FileLoader\\b3Serializer.cpp"']: no source file found
  `

**Comment by frerich** [comment]
Thanks! Indeed, that's a fairly long argument list! :-)

It indeed seems all sane to me up to `u'/Fo"Bullet2FileLoader.dir\Debug\\"` -- I suspect what's happening is that the backslashes (maybe because they are doubled for some reason?) cause the `"` to be ignored, so the following space does not end the `/Fo` argument but instead everything following this is considered to be part of the same argument -- including the source file argument!.

**Comment by sowsem** [comment]
It might be! And yeah quite a long command ;)

**Comment by webmaster128** [comment]
Turns out it is not the double backslash but the single backshash followed by a quote (`\"`). See #105

**Comment by sowsem** [comment]
Nice work guys!
