### ISSUE TITLE
Convert all names to snake_case?

### ISSUE THREAD

**Issue by webmaster128** [frerich/clcache#119]
According to the [PEP 8 style guide](https://www.python.org/dev/peps/pep-0008/#function-names), function names in Python should be written in camel_case. The same is true for different kind or variable names. clcache historically uses camelCase.

I have no string opinion about that matter but there are some minor points for and against applying that rule

* most symbols in the standard library are snake_case
* pylint default configuration expects snake_case (probably because of PEP 8)
* experienced Python developers are often used to snake_case

on the other hand

* renaming requires some amount of work
* git blame is going to be spammed by renaming changes

I would not put readability on any list because I think both are equally good when you're used to.

**Comment by frerich** [comment]
I tend to concur, using the PEP8 naming right from the start would have been a better choice but alas, history was different. By now, I also think that the benefits don't weigh heavy enough to warrant touching almost every single line of the source code.
