### ISSUE TITLE
What is the /vm argument?

### ISSUE THREAD

**Issue by webmaster128** [frerich/clcache#143]
In [optionsWithParameter](https://github.com/frerich/clcache/blob/f4748f6e9659308aece0365737468913dbfd8bca/clcache.py#L791), there is a /vm argument listed, which I cannot find in the MSVS documentation.

Instead there are a bunch of switches with that prefix: /vmb /vmg /vmm /vms /vmv, which are not parameters of /vm but independent arguments.

Can /vm go?

**Comment by webmaster128** [comment]
Same goes for /W

**Comment by frerich** [comment]
`/W` takes an argument, see e.g. the [Visual Studio 2008 documentation](https://msdn.microsoft.com/en-us/library/thxezb7y(v=vs.90).aspx). Both `/W4` as well as `/W 4` are legal, it seems.

**Comment by frerich** [comment]
As for `/vm`: I think it's wrong to consider it an option with an argument. `/vmm` is an option in itself, `/vm m` is not the same thing.

**Comment by webmaster128** [comment]
Thanks for pointing out the older MSVS version. /W takes an argument until including MSVS 2013 and was [changed with MSVS 2015](https://msdn.microsoft.com/en-us/library/thxezb7y(v=vs.140).aspx).

By the way, which one is the oldest MSVS version we are willing to support? I think there should be some official note on that in the README. That might be a question for the community (who ever that is). We're happy with MSVS 2015.

**Comment by webmaster128** [comment]
When we combine the signature from MSVS 2008-2013 (`/Wn` with `n = 0, ..., 4`) and the signature from MSVS 2015 (`/W0`, `/W1`, `/W2`, `/W3`, `/W4`) we can treat it just as `/NAMEparameter` in both cases and thus keep it in the list.
