### ISSUE TITLE
 3-clause bsd license applicable for the whole project?

### ISSUE THREAD

**Issue by hubx** [frerich/clcache#159]
Hi,

first of all thanks for this great project. Is the whole project under 3-clause BSD license or only the files which have a copyright notice on the top? If so, would you mind adding a LICENSE file? This would ease a contribution I would like to make that will help with #78

Thanks!

**Comment by webmaster128** [comment]
+1 for adding a project-global license file. You can consider all my work in this repo 3-clause BSD.

**Comment by frerich** [comment]
@hubx It's safe to consider the entire project subject to the BSD 3 clause license. I'm curious though, how would having a separate LICENSE file simplify your contribution?

I guess we could have a LICENSE file if only to shorten the preamble comment in `clcache.py`. Something like

> This file is part of the clcache project. Please see the accompanying LICENSE file for the license terms applicable to this source code.

Would be fine in each file, just if in doubt - of course, IANAL.

**Comment by hubx** [comment]
@frerich I wrote the code during work hours and there is process to bring it back here. One step is to ensure that projects and parts classify as OSS. Since you have some parts explicitly marked as BSD licensed in the source and some not (e.g. setup.py) I had concerns, that these fall under general copyright or a more restrictive license. A license file, or a reference in the README would erase any doubts here.

As for duplication, I think the BSD license is short enough to be included in every source code file. This is the approach mature projects such as https://github.com/freebsd/freebsd have. Other (newer? interpreter language?) projects such as django omit references to the license in the source and solely rely on a LICENSE file https://github.com/django/django/blob/master/LICENSE

**Comment by frerich** [comment]
@hubx as a start, I just extended the README file to mention that the entire source code of this project is - unless explicitly stated otherwise - subject to the BSD 3-clause license. I also added a LICENSE file and referenced it from all the `.py` source code files, I hope that clarifies the situation.
