### ISSUE TITLE
Visual Studio 2010

### ISSUE THREAD

**Issue by mellon85** [frerich/clcache#18]
I am trying to run clcache with Visual Studio 2010.

I have tried putting it inthe PATH of my user, of the whole system and even replacing my cl.exe with this launcher  and speicyfing CLCACHE_CL to the correct compiler (renamed to cl.real.exe). My code let me specify where to find clcache.py, plus I am having problems with py2exe and my windows is x86_64.

In the current setup I have these variable set
```
CLCACHE_DIR = C:\clcache
CLCACHE_CL = C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\cl.real.exe
CLCACHE_HARDLINK = 1
CLCACHE_LOG = 1
CLCACHE_PATH = C:\sources\clcache
```

```
#include <string>
#include <stdlib.h>

int main( int argc, char* argv[] )
{
    // Checking standard variables
    char *CLCACHE_PATH = getenv("CLCACHE_PATH");
    std::string cmd = "python "; 
    if (CLCACHE_PATH)
    {
        cmd += CLCACHE_PATH;
        cmd += '/';
    }
    cmd += "clcache.py ";
    for ( int i = 1; i < argc; ++i )
    {
        cmd += ' ';
        cmd += argv[i];
    }
    return system(cmd.c_str());
}
```

with the PATH modifications it wasn't being called, with this launcher I can manage to make it work if I manually call it, but visual studio will return me 

```
The system cannot execute the specified program.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\Platforms\Win32\Microsoft.Cpp.Win32.Targets(62,5): error MSB6006: "CL.exe" exited with code 1.
```

How can I setup Visual Studio 2010 to actually use clcache?

**Comment by webmaster128** [comment]
I was also having problems with py2exe, so I now use the following clcache.bat as my CXX

```
@echo off
@setlocal 

set CLCACHE_HARDLINK=1
set CLCACHE_NODIRECT=1

python.exe C:\Users\myuser\clcache-bin\clcache.py %*
```

Can this be closed? I guess it is getting too wide now.

**Comment by NicolasDorier** [comment]
@frerich I think your instructions are needlessly complicated for integration with visual studio.
You just have to integrate

```xml
<PropertyGroup>
    <CLToolExe>clcache.exe</CLToolExe>
    <CLToolPath>C:\ProgramData\chocolatey\bin\</CLToolPath>
    <TrackFileAccess>false</TrackFileAccess>
  </PropertyGroup>
```

In you project file.
