### ISSUE TITLE
clcache with Visual Studio 12 on AppVeyor

### ISSUE THREAD

**Issue by sasobadovinac** [frerich/clcache#180]
Hi! I have tried several different ways, both reasonable and unreasonable :) to set up clcache with Visual Studio 12 on AppVeyor to build FreeCAD, but it is still not working... Would someone have an idea what I am doing wrong or what else I could try? :\

Here is the build history, from build 1.0.131 onward https://ci.appveyor.com/project/sasobadovinac/freecad/history

**Comment by webmaster128** [comment]
In 131 everything looked good but doxygen was missing.

**Comment by webmaster128** [comment]
In 136, `clcache.bat` was not in PATH. It worked as long as `clcache.bat` was in the working directory but when you changed the working directory (via `cd "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\x86_amd64"`) it could not be found anymore.

**Comment by frerich** [comment]
@sasobadovinac Does it help to set the environment variables to use an absolute path to the `clcache.bat` file?

**Comment by sasobadovinac** [comment]
Thanks for taking the time to look at it and for the suggestions. I have since run a few more test builds in the test_appveyor_1 branch, but still no success. About the build 131, missing doxygen is expected, the real error is at line 185 and 187 since I have set the cmake variables wrong, have fixed that and also the mistake you pointed out in build 136 :) Absolute path also does not seem to help. Have also tried to set GLOBAL PROPERTY RULE_LAUNCH_COMPILE in CMakeLists.txt since this is how the ccache is used for linux builds, but also no luck...

I am at the moment guessing that the combination of cmake, cmake generator and msbuild is the problem and try to work around it. And I did manage to get some success if I just let cmake to prepare the build files and only after it, exchange the original cl.exe with the renamed clcache.exe. The problem I am however still having with this approach is "Failed to locate cl.exe on PATH (and CLCACHE_CL is not set), aborting" even when I am setting the CLCACHE_CL to cl_original.exe :\

https://ci.appveyor.com/project/sasobadovinac/freecad/build/1.0.182

Note that everything I tried before, at least as far as I can tell, the setup to clcache was overridden (original cl.exe was used) or it was recognized as "unknown compiler" or as "not able to compile a simple test program".

https://ci.appveyor.com/project/sasobadovinac/freecad/build/1.0.174
https://ci.appveyor.com/project/sasobadovinac/freecad/build/1.0.167

I will continue to search for a working solution and will report back if I find something, since it would be quite great if this would work, not just for the FreeCAD project, but laso for any other with a similar build setup and I am guessing it would also be good for AppVeyor since it would free some resources :)

**Comment by frerich** [comment]
@sasobadovinac It appears that the individual commands (e.g. `cd` and `set`) are all executed in separate command shells, i.e. an environment variable set via `set` does not influence subsequent statements. You could try this via e.g.

```
build-script:
  - set FOO=BAR
  - echo %FOO%
```

If this does not print `BAR` [the documentation](https://www.appveyor.com/docs/build-configuration#setting-environment-variables-in-build-script) is probably outdated.

Instead, try setting the environment variables in the `environment` section of your `appveyor.yml` file.

**Comment by sasobadovinac** [comment]
Yay, it is working https://ci.appveyor.com/project/sasobadovinac/freecad/build/1.0.190 I am just not quite sure why :) Setting the path with forward slashes seems to did the trick in the end, but I will play with it a bit more in the next days to try figure out what is the preferred setup in this case. Thanks for all the help and a great tool!

**Comment by frerich** [comment]
@sasobadovinac Glad to hear you got it working!
