### ISSUE TITLE
Harmonize naming in source code, introduce dedicated types

### ISSUE THREAD

**Issue by frerich** [frerich/clcache#187]
We're being somewhat inconsistent with the naming in the clcache source code, which is quite confusing. We recently started introducing manifest sections as well as cache sections to permit implementing a finer-grained locking strategy, but that didn't exactly make things any easier.

This ticket is meant to serve as a discussion forum for where we may want to go. Here's a moonshot idea:

The birds-eye view is that a `Cache` is made of an `ArtifactRepository` in which some sort of 'key' is mapped to an `CompilerArtifacts` value. And that value then provides access to whatever we cache. For the sake of finer-grained locking, we may have `ArtifactSections` which roughly correspond to `CacheSections`. So the API may be something like (read `::` as `has type` and `a -> b` as a function mapping a value of type `a` to a value of type `b`):

```
class Cache:
  artifactRepository :: ArtifactRepository
  manifestRepository :: ManifestRepository
  stats :: Statistics
  config :: Configuration

  clean :: void -> void

// Hmm, this class doesn't pull its own weight...
class ArtifactRepository:
    sections :: Generator<ArtifactSection>
    section :: Key -> ArtifactSection

// This class closely resembles a dictionary, maybe we could make good use of some Python-specific tricks such that we can write '<key> in <section>' or 'section[key]'.
class ArtifactSection:
    lock :: CacheLock
    hasArtifact :: Key -> Bool
    getArtifact :: Key -> CompilerArtifacts
    setArtifact :: (Key, CompilerArtifacts) -> void

class CompilerArtifacts:
    objectFilePath :: Path
    compilerStdout :: String
    compilerStderr :: String

class ManifestRepository:
  sections :: Generator<ManifestSection>
  section :: Key -> ManifestSection

class ManifestSection:
    lock :: CacheLock
    hasManifest :: Key -> Bool
    getManifest :: Key -> Manifest
    setManifest :: (Key, Manifest) -> void

class Configuration:
  // same as CacheConfiguration

class Statistics:
  // same as CacheStatistics
```

Not sure if it would work out, but I think there are two interesting observations here:

1. The `*Repository` classes don't really add much value. They just provide access to a sequence of sections (useful for operations which affect all sections, e.g. when cleaning the cache), and a shortcut for accessing a specific section. Right now, you can also clean both repositories independently - but is there a good reason for that other than just having a separate function for each? This could be achieved without having two classes, too...

2. The `*Section` classes are *very* similiar, and very dictionary-like. I wonder whether we really only need a generic `CacheSection` class which is somehow parametrised on the type of value it stores, and then that single class is used for both manifest as well as artifact sections.

**Comment by webmaster128** [comment]
Looks good so far. I would like to add consistency on one thing: ArtifactSection -> CompilerArtifactsSection. Then we have

**Manifest**
**Manifest**Section
**Manifest**Repository

and

**CompilerArtifacts**
**CompilerArtifacts**Section
**CompilerArtifacts**Repository

Both Manifest and CompilerArtifacts are a single entry represented by a unique key.

I would also use full names for long living objects:

cache.statistics
cache.configuration

Abbreviation will be used for short living objects like in a `with` statement.

**Comment by frerich** [comment]
Good points  👍
