### ISSUE TITLE
Recognize corrupted cache entries

### ISSUE THREAD

**Issue by TiloW** [frerich/clcache#263]
This came up during the discussion of #261. Sometimes cache entries are corrupted (e.g., when the compiler is forcibly terminated while copying an object file into the cache) which in most cases will lead to link errors as bad object files are delivered. It would be nice to find a way to prevent this.

One way to resolve this would be to mark entries that are being edited (e.g., by renaming files) and invalidate such marked entries upon lookup. Invalid entries need to be re-compiled.

**Comment by frerich** [comment]
@siu [wrote](https://github.com/frerich/clcache/pull/298#issuecomment-342203743) that merging #298 also resolves this issue, so let's close it.
