### ISSUE TITLE
Race condition when writing tlog files

### ISSUE THREAD

**Issue by dengste** [frerich/clcache#265]
clcache.exe is started through tracker.exe, which injects a DLL into the process so that it writes all read/written files to the transfer log (tlog) file on exit. When compiling in parallel, it seems that clcache is starting a separate cl.exe for every source file it receives on the commandline, whereas those would normally be compiled by one cl.exe process. This creates the problem that sometimes two or more clcache.exe processes will try to write to the same tlog-file, leading to an error message like this:

 [...] could not create the new file tracking log file:   [...].write.1u.tlog . The file exists.

Unfortunately, it is difficult to completely deactivate the writing of transfer logs (which are only needed for incremental building and cleaning). TrackFileAccess=false will only work for compilation, but not for custom build steps, where the writing of tlog files is hardcoded into the Microsoft.CppCommon.targets property sheet, which is installed together with MSBuild.

This is of course a bug in tracker.exe/msbuild and not in clcache, see

https://connect.microsoft.com/VisualStudio/feedback/details/1655214/msbuild-tracker-exe-race-condition-when-called-in-parallel-for-instances-of-the-same-exe

However, we would need some kind of workaround to make compilation more stable.

**Comment by frerich** [comment]
Which clcache version did you try? In the current version, v4.0.0, clcache no longer launches subprocesses (each of which handling a single source file). Instead, if uses a single process but multiple threads per file.

My understanding is that the `.tlog` file is only actually written at the end of the process, so maybe using v4.0.0 helps since there's only one process involved?

**Comment by dengste** [comment]
I'm using current master. Could this be a problem because I'm using a clcache.exe made with pyinstaller?
Anyway, I'm getting more confused because I don't see any of our custom build steps calling the compiler. I'll investigate further and get back to you, either by providing more information or by closing this bug.

**Comment by frerich** [comment]
I can't exclude the option that it's related to PyInstaller, but I think it's very unlikely. Since you mention PyInstaller, an unrelated note: it's known to generate [slow programs](https://github.com/frerich/clcache/wiki/Caveats#slow-performance-when-using-a-clcache-executable-built-via-pyinstaller) if called with unfortunate arguments. Maybe you'd like to make sure that this caveat does not apply to you. :-)

**Comment by TiloW** [comment]
Careful, are we speaking about calling clcache multiple times or just about calling the real compiler simultaneously? While the former should no longer occur when calling clcache once with multiple source files, the real compiler may still be invoked many times in parallel. In particular, it is to be expected that "clcache is starting a separate cl.exe for every source file it receives on the commandline".

**Comment by frerich** [comment]
> While the former should no longer occur when calling clcache once with multiple source files, the real compiler may still be invoked many times in parallel.

Ah, that's true - there will still be multiple `cl.exe` processes running concurrently. So this may well still be an issue after all. :-/

**Comment by dengste** [comment]
Yes, if you start cl.exe in parallel, you need to disable tlogs by compiling with /p:TrackFileAccess=false. I first had this in an override.props file which I included, but that did not seem to suffice. I haven't seen this problem again in the last week. As I mentioned above, even with TrackFileAccess=false you might see tlog files being written for custom build steps, but that should not matter as long as you don't call clcache in there.

**Comment by frerich** [comment]
I suspect there's not much we can do in clcache to fix this issue; for now, I [documented](https://github.com/frerich/clcache/wiki/Caveats#race-conditions-when-writing-to-tlog-files) the symptom.
