### ISSUE TITLE
Enable clcache in CMakeLists.txt

### ISSUE THREAD

**Issue by Zerophase** [frerich/clcache#273]
For make and other Linux build systems `ccache` works with `set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)` For nmake this doesn't work. Is there a means of enabling clcache through a variable in CMakeLists.txt?

**Comment by ivaigult** [comment]
You can try to hack `CLToolExe` and `CLToolPath` properties for every target.

```
function(any_target_hook)
    set(NON_COMPILE_TARGETS INTERFACE IMPORTED UNKNOWN ALIAS) 
    list(FIND NON_COMPILE_TARGETS "${ARGV1}" found)
    if (${found} GREATER -1)
        return()
    endif()
        
    set_target_properties(${ARGV0} PROPERTIES VS_GLOBAL_CLToolExe         "clcache.exe")
    set_target_properties(${ARGV0} PROPERTIES VS_GLOBAL_CLToolPath        "${CLCACHE_DIR}")
    set_target_properties(${ARGV0} PROPERTIES VS_GLOBAL_TrackFileAccess  "false")
endfunction()

function(add_library)
     _add_library(${ARGN})
     any_target_hook(${ARGN})
endfunction()

function(add_executable)
     _add_executable(${ARGN})
     any_target_hook(${ARGN})
endfunction()

```

**Comment by ivaigult** [comment]
Oh, wait. This works only for _msbuild_.

**Comment by Zerophase** [comment]
hmm, I'm using jom currently, since it seems to give the best build times.

**Comment by frerich** [comment]
Some [StackOverflow answer](http://stackoverflow.com/a/37828605/91757) suggests that, as of CMake 3.4, passing something like

```
-DCMAKE_CXX_COMPILER_LAUNCHER=clcache
```

on the command line may work. It's not clear to me though whether this also works with NMake.

I suspect this question may yield better replies when asked in some CMake forum - unfortunately, I'm not very familiar with CMake myself.

**Comment by frerich** [comment]
In case you find something though, it would be great if you could share your finding such that we could add it to the Wiki.

**Comment by frerich** [comment]
@Zerophase Did you find any way to make this work with CMake? I'd like to close this ticket since I suspect that there's not much to be done here but if you found something interesting, I'd love to add that to the Wiki for other clcache users to benefit from. :-)

**Comment by Zerophase** [comment]
@frerich It might be working I got it to compile, but I'm not sure if it's actually using clcache.

This breaks compilation:
```cmake
set(CMAKE_CXX_COMPILER_LAUNCHER "path/to/clcache.exe")
```
This allows the project to compile, but I don't know if clcache is actually getting run: (I use the same for ccache)
```cmake
set(GLOBAL PROPERTY RULE_LAUNCH_COMPILE "path/to/clcache.exe")
set(GLOBAL PROPERTY RULE_LAUNCH_LINK "path/to/clcache.exe")
```

**Comment by frerich** [comment]
@Zerophase You could check whether clcache kicks in by checking the stats before & after a build (by running `clcache -s`).

**Comment by Zerophase** [comment]
Yeah, it doesn't kick in.

**Comment by frerich** [comment]
Pity - I'm closing this issue, I suspect it's more suitable for a CMake forum.

**Comment by brianlheim** [comment]
Hey, see this blog post: https://crascit.com/2016/04/09/using-ccache-with-cmake/. RULE_LAUNCH_COMPILE and CMAKE_CXX_COMPILER_LAUNCHER don't work with non-Ninja/Makefile generators, so people have run into a similar problem using XCode on macOS. We use the workaround for XCode in our project (https://github.com/supercollider/supercollider/pull/3136) and I bet it has a good chance of working on Windows with clcache. I haven't tried it yet, but I was thinking of giving it a go when I set up appveyor for our project.

**Comment by feliwir** [comment]
This is not a CMake issue, but much more a design issue of clcache. Your integration page states that CC/CXX environment variables should be set before running cmake, but it should definetly be possible to tell cmake to use clcache from within a CMakeList, As stated before with ccache this is possible like this: `set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)`, which puts ccache before the actual compile command. CCache should behave similar and not try to find CL.exe by itself in my opinion.

**Comment by akleber** [comment]
ccache works by prefixing the compile command or masquerading as the compiler. clcache only supports masquerading.
CMake's CMAKE_CXX_COMPILER_LAUNCHER variable or RULE_LAUNCH_COMPILE property prefix the compiler with this command.
So as CMake only supports the prefix method and clcache only supports the masquerade method, CMAKE_CXX_COMPILER_LAUNCHER/RULE_LAUNCH_COMPILE does not work with clcache currently.
For me the integration method via "wrapper batch file" described in the wiki https://github.com/frerich/clcache/wiki/Integration works fine. However for an even smoother CMake integration I would love to see the prefixing method in clcache.

**Comment by timblechmann** [comment]
@frerich i'm wondering if clcache could simply bring a launcher script? could be something as simple as converting the first argument to a `CLCACHE_CL` environment variable and calling clcache.exe with the remaining arguments.
since it's not entirely trivial to write such a stript in `bat` it would be very handy. if it's a first-class member of clcache one could even use `find_program` in cmake to detect it and use it when it's available

**Comment by timblechmann** [comment]
possibly helpful wrapper: https://gitlab.com/timblechmann/clcache-launcher
