### ISSUE TITLE
option to ignore /Zi

### ISSUE THREAD

**Issue by predmond** [frerich/clcache#28]
There should be an option (enabled with an environment variable perhaps) to ignore (eat) unsupported options like /Zi.

Perhaps this could work with /Yu too (precompiled headers)

**Comment by jdonald** [comment]
This is PR #21. I am in support of this for the reasons I stated there.

**Comment by frerich** [comment]
Closing this; PR #21 implemented support for ignoring `Yu`. For `Zi`, my understanding is that clcache can actually be made to support it, but there's issue ticket #30 already to deal with that. So this ticket seems to provide no additional purpose anymore.
