### ISSUE TITLE
Feature request: monkeypatch distutils to use clcache

### ISSUE THREAD

**Issue by xoviat** [frerich/clcache#284]
clcache should provide a module that when imported, monkeypatches distutils c compiler to use clcache.

**Comment by frerich** [comment]
I'm not familiar with `distutils` really, let alone how it uses the C compiler. Can you elaborate on what the issue is and how monkeypatching would help?

**Comment by xoviat** [comment]
See https://stackoverflow.com/questions/11013851/speeding-up-build-process-with-distutils second answer. The problem is that the answer has suffered bit rot because it wasn't tested.

**Comment by xoviat** [comment]
To clarify further, this should be done with a .pth file. That loads clcache during startup.
