### ISSUE TITLE
all modules not included in setup.py

### ISSUE THREAD

**Issue by xoviat** [frerich/clcache#288]
Appveyor failure is the following:
```

python : Traceback (most recent call last):
At line:3 char:1
+ python setup.py build
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Traceback (most recent call last)::String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
  File "C:\Python33\Scripts\clcache-script.py", line 9, in <module>
    load_entry_point('clcache==4.1.1.dev25+g22457ee', 'console_scripts', 'clcache')()
  File "c:\python33\lib\site-packages\clcache.py", line 1508, in main
    cache = Cache()
  File "c:\python33\lib\site-packages\clcache.py", line 575, in __init__
    from storage import CacheFileWithMemcacheFallbackStrategy
ImportError: No module named 'storage'
```

The cause of this failure is that `storage` is not included in `setup.py`. However, the problem is that `storage` is too generic of a module name. This is normally handled by moving the modules into a dedicated package to avoid namespace conflicts.

However, that brings up another issue: you're (or others) probably just copying the clcache files into a folder on the PATH. This might not work any longer if we use a dedicated package, but the general method of redistributing code is to use setup.py / the standard package layout and `pip install`.

The question is: would you be open to moving to a package named `clcache` with a `__main__.py` file inside, along with the other modules?

**Comment by frerich** [comment]
I don't mind (justified) reorganisations of the source code at all. I'd prefer keeping backwards compatibility (with existing setups) though, of course.

Would it be possible to keep a `clcache.py` wrapper script which merely imports the `clcache` package and invokes a main function?

**Comment by xoviat** [comment]
@frerich I don't think so because it would have the same name as the package. We could rename the package though.
