### ISSUE TITLE
compile would run slower with clcache, or?

### ISSUE THREAD

**Issue by simonhf** [frerich/clcache#3]
I tried the following: compiling one of my .c files using cl.exe without clcache. It took 0.7 seconds. I then tried compiling again with the /e command line option. And again with the /ep command line option. These 'compiles' took 1.4 and 1.8 seconds respectively. Based on this evidence, how does clcache speed up the compile if running cl.exe with the /ep option causes cl.exe to run twice as slow? Have I missed the point somehow? Please note that I didn't actually use clcache for my little performance test... I was just testing the theory to see if clcache could be faster...

**Comment by JulianVolodia** [comment]
hmm... (accidently found that and have idea ;) )

What I see, lag with starting apps on Windows, when SSD device is present. I have quite big difference when changing 

Probably you don't know now, but SuperFetch, PreFetch is set up to which option? :)
http://www.tomshardware.com/reviews/ssd-performance-tweak,2911-5.html ?

Is that problem a live issue still?

**Comment by frerich** [comment]
This ticket doesn't seem to go anywhere, closing this.
