### ISSUE TITLE
Appveyor builds failing (pylint, pip, etc.)

### ISSUE THREAD

**Issue by jimbo1qaz** [frerich/clcache#316]
```
pylint --rcfile=.pylintrc --disable=no-member tests\test_integration.py
Using config file C:\projects\clcache\.pylintrc
************* Module test_integration
C: 24, 0: third party import "import pytest" should be placed before "from clcache import __main__ as clcache" (wrong-import-order)
```

I patched around this issue on https://github.com/jimbo1qaz/clcache/commits/master (but Appveyor still fails later on.)

```
codecov.exe : The filename, directory name, or volume label syntax is incorrect.
At line:9 char:1
+ & codecov --no-color -X gcov -F unittests -e PYTHON_INSTALL
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (The filename, d...x is incorrect.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
```

https://ci.appveyor.com/project/jimbo1qaz/clcache/build/1.0.7/job/798opi9e23fious7

-------

I also fixed an issue where `pip install -U pip setuptools wheel` pip would try to upgrade itself, and be unable to overwrite pip.exe. I changed to the Python-recommended `python -m pip install -U pip setuptools wheel`.

**Comment by frerich** [comment]
The CI builds seem to work again.
