### ISSUE TITLE
4.2.0 PyPI release?

### ISSUE THREAD

**Issue by nicoddemus** [frerich/clcache#325]
Hi @frerich,

Would it be possible to publish the latest release to PyPI?

I'm one of the maintainers of the [conda-forge recipe](), and it would be great to update it to download from PyPI instead of from GitHub. 👍

**Comment by frerich** [comment]
I now found that a PyPi account by the name of [ghost555](https://pypi.org/user/ghost555/) appears to be the maintainer of the existing clcache package. I suppose it is an alias of xoviat. I'll try to get in touch with him and see whether he would be willing to transfer (or share) the ability to upload new versions.

**Comment by nicoddemus** [comment]
Hi @frerich,

Oh I thought it was just a fluke that the package was not published.

To publish the package ideally one would do in a virtual environment:

```
pip install wheel twine
python setup.py bdist_wheel sdist
twine upload dist\*
```

`python setup.py upload` is no longer recommended because it sends the password in plain text to the server, which is not secure.

---

Indeed `@xoviat` has deleted his GitHub account, that user handle is familiar to me from other projects. On PyPI it appears the mainteiner is https://pypi.org/user/ghost555/, which looks like a placeholder for a deleted account.

Oh well, it seems there's nothing that can be done until the claim process is laid out. 😕

**Comment by frerich** [comment]
@nicoddemus By the way, I must admit that I indeed forgot about the PyPI package at first -- which is why I now decided to write down a [Release Checklist](https://github.com/frerich/clcache/wiki/Release-Checklist). I just don't do releases often enough to remember all the steps. :-)

**Comment by nicoddemus** [comment]
Heh fair enough! 😁

**Comment by frerich** [comment]
clcache v4.2.0 is now available on PyPI. :-)
