### ISSUE TITLE
Option to compress cache content

### ISSUE THREAD

**Issue by benjaminfuchs** [frerich/clcache#327]
Hi,
I was wondering if it is possible to add an option to compress the content stored in the cache like ccache has (look for CCACHE_COMPRESS here: https://ccache.samba.org/manual/latest.html).

Where in the code would be the entry point for such a feature?
If this is a good idea I would try to create a first implementation.

**Comment by frerich** [comment]
#328 was just merged, so I guess this can be closed now.
