### ISSUE TITLE
Trojan/Virust in clcache.exe?

### ISSUE THREAD

**Issue by simplewhy** [frerich/clcache#336]
Is there a virus in [https://github.com/frerich/clcache/releases/download/v4.2.0/clcache-4.2.0.zip](https://github.com/frerich/clcache/releases/download/v4.2.0/clcache-4.2.0.zip)
in file clcache.exe?

There are 7/70 detections on virustotal:
[https://www.virustotal.com/#/file/cdce3e0289156c6fa7cccb1986a8782c0dc4987bf80ffd6f5d9b39271dfc53e9/detection](https://www.virustotal.com/#/file/cdce3e0289156c6fa7cccb1986a8782c0dc4987bf80ffd6f5d9b39271dfc53e9/detection)

**Comment by frerich** [comment]
Given that only 7 out of 70 engines report that there is a virus, I suspect this is an issue with those few virus scanners. Indeed, looking at pyinstaller/pyinstaller#603 suggests that this is a known issue: a few virus scanners incorrectly detect the code generated by PyInstaller as containing a virus.

Hence, I'm fairly confident that this is a false alert.
