### ISSUE TITLE
Renaming build directory cause cache misses

### ISSUE THREAD

**Issue by 9a4gl** [frerich/clcache#345]
I am trying to integrate clcache with Jenkins, for each branch Jenkins do create directory that has new unique name. If using clcache to build there is no cache hits because it looks like current directory name is used for hash.

I did also following experiment. I did built my project, then I renamed directory of my project and then I get cache misses. Is there solution to this ? 

BR,
Tihomir

**Comment by benjaminfuchs** [comment]
@9a4gl Haven't used the feature yet but `CLCACHE_BASEDIR` seems to be what your looking for. More info is in the [README](https://github.com/frerich/clcache/blob/master/README.asciidoc).

**Comment by 9a4gl** [comment]
Hm, looks so, why I missed that. Going to try right now.
