### ISSUE TITLE
Minimal Python version?

### ISSUE THREAD

**Issue by webmaster128** [frerich/clcache#37]
Hi everyone,

is there any official minimum Python version for this project?

If we could use Python 2.7+ would be good because it allows nice stiff like [new string formatting](https://pyformat.info/) or [argparse](https://docs.python.org/2/library/argparse.html#module-argparse).

Thanks.

**Comment by frerich** [comment]
No, there's no official minimum Python version. I believe it's safe to claim that everyone was already using Python 2.7 anyway (or that upgrading to Python 2.7 wouldn't be a problem) so I'm fine with requiring Python 2.7.

**Comment by webmaster128** [comment]
Great, so we have one now :)
