### ISSUE TITLE
Why pickle?

### ISSUE THREAD

**Issue by webmaster128** [frerich/clcache#62]
Is there any good reason, we're using pickle to store the manifests?

As far as I can see, pickle does nothing else than storing and loading python structures like
```
[
    [
        'path/to/include1',
        'path/to/include2',
    ],
    [
        'include1Hash',
        'include2Hash',
    ]
]
```
in text format with some binary separator magic.

Wouldn't it be much more maintainable to store those manifests as JSON? JSON is a format, we already use, everyone is familiar with and that is highly human readable. There is a good chance that the empty includes lists found in #58 would have been noted earlier when the storage format was easier to debug.

**Comment by frerich** [comment]
I assumed it was done for performance reasons: the [original commit](8ef858a8c9147f5706ba829fc5532ada30a35785) used `cPickle` instead of the default `pickle`. @vchigrin might remember the details.

**Comment by webmaster128** [comment]
Okay. But why did you close this?

**Comment by frerich** [comment]
I felt like I answered the question `Why pickle?`, which is what this "issue" is about, to the best of my knowledge. What predicate would you expect me to use for deciding whether this issue can be closed or not? :-)

**Comment by webmaster128** [comment]
Well (in this case) we have some idea, of why it was used. But you do not really know why it is in the code. Let's give vchigrin a chance to answer himself. If there are not any good reasons to use pickle in particular, we should consider moving to JSON for the reasons I mentioned.

**Comment by Jimilian** [comment]
Hi, guys! Please, don't move to `json`. It's too slow. Here is [results](http://stackoverflow.com/questions/9662757/python-performance-comparison-of-using-pickle-or-marshal-and-using-re/38031241#38031241) of my benchmark. I think in clcache case it's better to use `marshal`, because it should be faster. Especially in Python2.7.
