### ISSUE TITLE
parseIncludesList regex only working for english locale

### ISSUE THREAD

**Issue by timblechmann** [frerich/clcache#65]
the english compiler output is "Note: including file", though the german language output is "Hinweis: Einlesen der Datei" ... not idea about non-european languages ...

cotire seems to have some code, which might help:
https://github.com/facebook/hhvm/blob/master/CMake/cotire.cmake#L898

**Comment by frerich** [comment]
I guess for testing this, we'd need to hardcode some non-English output of `cl.exe` in the tests - or is it possible to configure a language on the command line (maybe via some environment variable)?

**Comment by webmaster128** [comment]
> or is it possible to configure a language on the command line (maybe via some environment variable)?

I don't think so. Even on a German Windows system I had to manually install the German MSVC language package and use a newly created German terminal shortcut to get German compiler output.

**Comment by timblechmann** [comment]
cool, thanks for the quick fix!
