### ISSUE TITLE
py2exe on windows 8 and Python 2.7.10 produces crashing exe

### ISSUE THREAD

**Issue by tfar** [frerich/clcache#84]
Running `python setup.py py2exe` lists the following output after compiling the bytecode, and produces a clcache.exe that crashes when executed. Any ideas how to debug this?

```
*** copy extensions ***
*** copy dlls ***
copying C:\Python27\lib\site-packages\py2exe\run.exe -> C:\clcache-master\dist\clcache.exe
Adding python27.dll as resource to C:\clcache-master\dist\clcache.exe
warning: py2exe: Version Info will not be included:
  could not parse version number '3.0.3-dev'

The following modules appear to be missing
['_scproxy', '_sysconfigdata', 'dummy.Process']

*** binary dependencies ***
Your executable(s) also depend on these dlls which are not included,
you may or may not need to distribute them.

Make sure you have the license if you distribute any of them, and
make sure you don't distribute files belonging to the operating system.

   OLEAUT32.dll - C:\Windows\system32\OLEAUT32.dll
   USER32.dll - C:\Windows\system32\USER32.dll
   SHELL32.dll - C:\Windows\system32\SHELL32.dll
   ole32.dll - C:\Windows\system32\ole32.dll
   ADVAPI32.dll - C:\Windows\system32\ADVAPI32.dll
   WS2_32.dll - C:\Windows\system32\WS2_32.dll
   GDI32.dll - C:\Windows\system32\GDI32.dll
   KERNEL32.dll - C:\Windows\system32\KERNEL32.dll

C:\clcache-master>dist\clcache.exe
```

**Comment by webmaster128** [comment]
Could you try using the 3.0.2 release instead of the master branch? https://github.com/frerich/clcache/releases

**Comment by webmaster128** [comment]
Hmm okay, sorry. The invalid version number "3.0.3-dev" is only a warning and should not be the reason for crashes.

**Comment by frerich** [comment]
@tfar can you reproduce this? If so, do you get any error output from runniing `dist\clcache.exe`?

**Comment by frerich** [comment]
I just read that `py2exe` is quited dated (according to [the news](http://www.py2exe.org/index.cgi/News) the last release was in 2008!). [PyInstaller](http://www.pyinstaller.org) seems to be more active and according to some [random blog article](https://mborgerson.com/creating-an-executable-from-a-python-script) I found, creating an installer should be not much more difficult than with `py2exe` (and no separate `setup.py` file is needed). So maybe that would be a good thing to try.

**Comment by tfar** [comment]
Will give that a try. Thanks.

**Comment by frerich** [comment]
@tfar I'm curious, how did your experiment with PyInstaller go? If it helped for you, I might just switch to it (given that it seems to be more active anyway).

**Comment by tfar** [comment]
After `pip install pyinstaller` and `pyinstaller --onefile clcache.py`, the resulting `clcache.exe` in the dist folder worked just fine.

**Comment by frerich** [comment]
Sounds like we should recommend `pyinstaller` in favor of `py2exe` indeed!
